{{-- Menu proposal of the consultation: the saved one (MealPlan) or one generated by the expert service. --}}
@php
    $canEdit = auth()->user()->can('create', \App\Models\Diagnosis::class);
    $draftQuery = array_filter(['variante' => $variant ?: null, 'dias' => $days > 1 ? $days : null]);
@endphp

<div class="mt-4" id="meal-plan">
    <div class="d-flex flex-wrap align-items-center gap-2 mb-2">
        <h5 class="mb-0">{{ __('Propuesta de menú') }}</h5>
        @if ($savedPlan)
            <span class="badge bg-gradient-success">{{ __('Guardada') }}</span>
            <span class="text-xs text-secondary">
                {{ __('el :date', ['date' => $savedPlan->updated_at->format('d/m/Y H:i')]) }}
                @if ($savedPlan->author) {{ __('por :name', ['name' => $savedPlan->author->name]) }} @endif
                @if ($savedPlan->edited) · {{ __('ajustada a mano') }} @endif
            </span>
        @elseif ($mealPlan)
            <span class="badge bg-gradient-secondary">{{ __('Sin guardar') }}</span>
            <span class="text-xs text-secondary">{{ __('generada automáticamente por programación lineal') }}</span>
        @endif

        @if ($canEdit && $mealPlan)
            <div class="ms-auto d-flex flex-wrap gap-2">
                @if ($savedPlan)
                    <a href="{{ route('meal-plan.edit', $diagnosis) }}" class="btn btn-sm btn-primary mb-0">{{ __('Ajustar') }}</a>
                    <a href="{{ route('meal-plan.edit', ['diagnosis' => $diagnosis, 'nueva' => 1]) }}" class="btn btn-sm btn-outline-primary mb-0">{{ __('Generar nueva propuesta') }}</a>
                    {{-- #meal-plan-discard-form is outside the page form (forms cannot be nested). --}}
                    <button type="submit" form="meal-plan-discard-form" class="btn btn-sm btn-outline-danger mb-0" onclick="return confirm('{{ __('¿Descartar la propuesta guardada?') }}')">{{ __('Descartar') }}</button>
                @else
                    <a href="{{ route('meal-plan.edit', ['diagnosis' => $diagnosis, 'nueva' => 1, ...$draftQuery]) }}" class="btn btn-sm btn-primary mb-0">{{ __('Revisar y guardar') }}</a>
                    <a href="{{ route('result', ['diagnosis' => $diagnosis, 'variante' => $variant + 1, 'dias' => $days > 1 ? $days : null]) }}#meal-plan" class="btn btn-sm btn-outline-primary mb-0">{{ __('Otra variante') }}</a>
                    <div class="btn-group" role="group" aria-label="{{ __('Días') }}">
                        @foreach ([1, 3, 7] as $n)
                            <a href="{{ route('result', ['diagnosis' => $diagnosis, 'variante' => $variant ?: null, 'dias' => $n > 1 ? $n : null]) }}#meal-plan"
                               @class(['btn btn-sm mb-0', 'btn-secondary' => $days === $n, 'btn-outline-secondary' => $days !== $n])>{{ trans_choice(':n día|:n días', $n, ['n' => $n]) }}</a>
                        @endforeach
                    </div>
                @endif
            </div>
        @endif
    </div>

    @error('menu')
        <p class="text-sm text-danger">{{ $message }}</p>
    @enderror

    @if (! $mealPlan)
        <p class="text-sm text-secondary">
            {{ $diagnosis->result_pulgar && $diagnosis->carbohydrate && $diagnosis->protein && $diagnosis->lipido
                ? __('El sistema experto no está disponible para generar la propuesta.')
                : __('Para generar la propuesta, la consulta necesita requerimiento energético y gramos de carbohidratos, proteínas y lípidos.') }}
        </p>
    @elseif (empty($mealPlan['days']))
        <p class="text-sm text-warning">{{ implode(' ', $mealPlan['notes']) }}</p>
    @else
        <p class="text-xs text-secondary mb-2">
            {{ __('Porciones de intercambio ajustadas al requerimiento de la consulta, con al menos 3 porciones de verduras, 2 de frutas y 2 a 3 de lácteos al día.') }}
        </p>
        @include('meal_plans._days', ['plan' => $mealPlan, 'tabsId' => 'result-days'])
    @endif
</div>
