{{-- Menu generated by linear programming in the expert service (ExpertDiagnosisService::mealPlan). --}}
@php
    $nutrients = ['energy' => ['Energía', 'kcal'], 'carbohydrates' => ['Carbohidratos', 'g'], 'proteins' => ['Proteínas', 'g'], 'fats' => ['Grasas', 'g']];
    $number = fn ($v) => rtrim(rtrim(number_format($v, 1, ',', '.'), '0'), ',');
    $portions = fn ($p) => $number($p).' '.($p == 1 ? __('porción') : __('porciones'));
@endphp

<div class="mt-4" id="meal-plan">
    <div class="d-flex flex-wrap align-items-baseline gap-2 mb-2">
        <h5 class="mb-0">{{ __('Plan alimentario generado') }}</h5>
        @if ($mealPlan)
            <a href="{{ route('result', ['diagnosis' => $diagnosis, 'variante' => $variant + 1]) }}#meal-plan" class="btn btn-sm btn-outline-primary ms-auto mb-0">{{ __('Otra variante') }}</a>
        @endif
    </div>

    @if (! $mealPlan)
        <p class="text-sm text-secondary">
            {{ $diagnosis->result_pulgar && $diagnosis->carbohydrate && $diagnosis->protein && $diagnosis->lipido
                ? __('El sistema experto no está disponible para generar el plan.')
                : __('Para generar el plan, la consulta necesita requerimiento energético y gramos de carbohidratos, proteínas y lípidos.') }}
        </p>
    @elseif (empty($mealPlan['meals']))
        <p class="text-sm text-warning">{{ implode(' ', $mealPlan['notes']) }}</p>
    @else
        <p class="text-xs text-secondary mb-2">
            {{ __('Porciones de intercambio elegidas por programación lineal para cumplir el requerimiento de la consulta, con al menos 3 porciones de verduras, 2 de frutas y 2 a 3 de lácteos al día.') }}
        </p>
        <div class="row g-3 mb-3">
            @foreach ($nutrients as $key => [$label, $unit])
                @php($deviation = $mealPlan['deviation_percent'][$key])
                <div class="col-6 col-md-3">
                    <div class="border border-radius-lg p-2 h-100">
                        <p class="text-xs text-uppercase text-secondary font-weight-bolder mb-0">{{ $label }}</p>
                        <span class="text-sm font-weight-bold">{{ $number($mealPlan['totals'][$key]) }} {{ $unit }}</span>
                        <span class="text-xs text-secondary">/ {{ $number($mealPlan['targets'][$key]) }}</span>
                        <span @class(['text-xs', 'text-success' => abs($deviation) <= 5, 'text-warning' => abs($deviation) > 5])>
                            ({{ $deviation > 0 ? '+' : '' }}{{ $number($deviation) }} %)
                        </span>
                    </div>
                </div>
            @endforeach
            {{-- Results of an older service have no ceilings. --}}
            @foreach (['glycemic_load' => ['Carga glucémica', ''], 'saturated_fat' => ['Grasa saturada', 'g']] as $key => [$label, $unit])
                @isset($mealPlan['limits'][$key])
                    @php($within = $mealPlan['totals'][$key] <= $mealPlan['limits'][$key] * 1.02)
                    <div class="col-6 col-md-3">
                        <div class="border border-radius-lg p-2 h-100">
                            <p class="text-xs text-uppercase text-secondary font-weight-bolder mb-0">{{ $label }}</p>
                            <span class="text-sm font-weight-bold">{{ $number($mealPlan['totals'][$key]) }} {{ $unit }}</span>
                            <span @class(['text-xs', 'text-success' => $within, 'text-warning' => ! $within])>/ {{ __('máx.') }} {{ $number($mealPlan['limits'][$key]) }}</span>
                        </div>
                    </div>
                @endisset
            @endforeach
        </div>

        <div class="row g-3">
            @foreach ($mealPlan['meals'] as $meal)
                <div class="col-md-6 col-xl-4">
                    <div class="border border-radius-lg p-3 h-100">
                        <div class="d-flex align-items-baseline mb-1">
                            <strong class="text-sm">{{ $meal['label'] }}</strong>
                            <span class="text-xs text-secondary ms-auto">{{ $number($meal['totals']['energy']) }} / {{ $meal['energy_target'] }} kcal</span>
                        </div>
                        <ul class="list-unstyled mb-0 text-sm">
                            @foreach ($meal['items'] as $item)
                                <li>
                                    {{ $item['name'] }}:
                                    <strong>{{ $item['grams'] ? $item['grams'].' g' : $portions($item['portions']) }}</strong>
                                    <span class="text-xs text-secondary">({{ $portions($item['portions']) }} · {{ $item['group'] }})</span>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endforeach
        </div>

        @foreach ($mealPlan['notes'] as $note)
            <p class="text-xs text-warning mb-0 mt-2">{{ $note }}</p>
        @endforeach
    @endif
</div>
