<?php

namespace App\Services;

use App\Models\Diagnosis;
use App\Models\Food;
use App\Models\MealPlan;
use App\Models\Patient;
use App\Models\User;
use Illuminate\Support\Collection;

/**
 * Menu proposals of a consultation: generated by the expert service (linear programming,
 * expert/app/meal_plan.py), adjusted by the doctor and saved. Plans have the shape of
 * MealPlan in expert/app/responses.py: targets, limits and one menu per day.
 */
class MealPlanService
{
    public const NUTRIENTS = ['energy', 'carbohydrates', 'proteins', 'fats'];

    public const REPORTED = [...self::NUTRIENTS, 'glycemic_load', 'saturated_fat'];

    public function __construct(private ExpertDiagnosisService $expert)
    {
    }

    /**
     * The energy and grams the doctor set in the consultation; null when incomplete.
     */
    public function targets(Diagnosis $diagnosis): ?array
    {
        $targets = [
            'energy' => (float) $diagnosis->result_pulgar,
            'carbohydrates' => (float) $diagnosis->carbohydrate,
            'proteins' => (float) $diagnosis->protein,
            'fats' => (float) $diagnosis->lipido,
        ];

        return $targets['energy'] < 800 || in_array(0.0, $targets, true) ? null : $targets;
    }

    /**
     * Glycemic load and saturated fat ceilings of the patient's macronutrient plan, or the
     * general ones (the same defaults as the expert service) when there is none.
     *
     * @param  array|null  $evaluation  ExpertDiagnosisService::evaluate() of the consultation, when at hand
     */
    public function limits(Diagnosis $diagnosis, array $targets, ?array $evaluation = null): array
    {
        $evaluation ??= ($patient = Patient::find($diagnosis->id_patient)) ? $this->expert->evaluate($diagnosis, $patient) : null;
        $patientLimits = collect($evaluation['result']['macronutrients']['limits'] ?? [])
            ->only(['glycemic_load', 'saturated_fat'])
            ->map(fn (array $limit) => $limit['amount'])
            ->all();

        return [
            'glycemic_load' => config('clinical.nutrition.glycemic_load.base'),
            'saturated_fat' => round($targets['energy'] * config('clinical.nutrition.saturated_fat_pct.base') / 900),
            ...$patientLimits,
        ];
    }

    /**
     * New proposal from the expert service; null without targets or when the service fails.
     *
     * @param  int  $variant  another variant, another menu with the same targets
     * @param  int  $days  menus, different from each other
     * @param  int|null  $budget  CLP per day
     */
    public function generate(Diagnosis $diagnosis, int $variant = 0, int $days = 1, ?array $evaluation = null, ?int $budget = null): ?array
    {
        if (! ($targets = $this->targets($diagnosis)) || ! config('services.expert.url')) {
            return null;
        }

        return $this->expert->requestMealPlan([
            'targets' => $targets,
            'foods' => $this->catalog()->map(fn (Food $food) => $this->foodPayload($food))->values()->all(),
            'limits' => $this->limits($diagnosis, $targets, $evaluation),
            'seed' => $diagnosis->id * 1000 + $variant,
            'days' => $days,
            'allergies' => $this->allergies($diagnosis),
            'budget' => $budget,
        ], ['diagnosis' => $diagnosis->id]);
    }

    /**
     * Allergies and intolerances of the clinical record, as the doctor wrote them: the expert
     * service recognizes the allergens in the text (expert/app/allergies.py).
     */
    public function allergies(Diagnosis $diagnosis): array
    {
        $text = trim((string) Patient::find($diagnosis->id_patient)?->clinicalRecord?->food_allergies);

        return $text === '' ? [] : [mb_substr($text, 0, 500)];
    }

    /**
     * A plan from the doctor's choices, with every amount recomputed from the catalog
     * (nothing the browser computed is trusted).
     *
     * @param  array  $days  [{meals: [{key, items: [{food_id, portions}]}]}], validated by SaveMealPlanRequest
     * @param  bool  $edited  changed by the doctor (status "editado") or saved as generated ("generado")
     */
    public function rebuild(Diagnosis $diagnosis, array $days, ?array $evaluation = null, bool $edited = true): array
    {
        $targets = $this->targets($diagnosis);
        $foods = $this->catalog();

        $plan = [];
        foreach (array_values($days) as $index => $day) {
            $chosen = collect($day['meals'] ?? [])->keyBy('key');
            $meals = collect(config('clinical.meal_plan.meals'))->map(function (array $meal) use ($chosen, $foods, $targets) {
                $items = collect($chosen[$meal['key']]['items'] ?? [])
                    ->map(fn (array $item) => $this->item($foods[(int) $item['food_id']], (float) $item['portions']))
                    ->values()->all();

                return [
                    'key' => $meal['key'],
                    'label' => $meal['label'],
                    'energy_target' => (int) round($targets['energy'] * $meal['energy_share'] / 100),
                    'items' => $items,
                    'totals' => $this->sum($items),
                ];
            })->all();

            $totals = $this->sum(array_column($meals, 'totals'));
            $plan[] = [
                'day' => $index + 1,
                'meals' => $meals,
                'totals' => $totals,
                'deviation_percent' => collect(self::NUTRIENTS)
                    ->mapWithKeys(fn ($key) => [$key => round(($totals[$key] - $targets[$key]) / $targets[$key] * 100, 1)])
                    ->all(),
                'notes' => [],
            ];
        }

        return [
            'status' => $edited ? 'editado' : 'generado',
            'seed' => null,
            'targets' => $targets,
            'limits' => $this->limits($diagnosis, $targets, $evaluation),
            'days' => $plan,
            'notes' => [],
        ];
    }

    public function save(Diagnosis $diagnosis, array $plan, User $author, bool $edited): MealPlan
    {
        return MealPlan::updateOrCreate(
            ['diagnosis_id' => $diagnosis->id],
            ['plan' => $plan, 'edited' => $edited, 'created_by' => $author->id],
        );
    }

    /**
     * Foods the doctor can choose in the editor, grouped like the catalog, with their
     * nutrients per portion for the live totals.
     */
    public function editorCatalog(): array
    {
        return $this->catalog()
            ->filter(fn (Food $food) => (float) $food->kcal > 0)
            ->map(fn (Food $food) => [
                'id' => $food->id,
                'name' => $food->name ?: $food->item,
                'group' => $food->item,
                'grams' => (float) $food->gr ?: null,
                ...$this->perPortion($food),
            ])
            ->sortBy(['group', 'name'])
            ->values()->all();
    }

    /**
     * @return Collection<int, Food> keyed by id
     */
    private function catalog(): Collection
    {
        return Food::all()->keyBy('id');
    }

    /**
     * Food of MealPlanRequest in expert/app/schemas.py.
     */
    private function foodPayload(Food $food): array
    {
        return [
            'id' => $food->id,
            'name' => $food->name ?: $food->item,
            'item' => $food->item,
            'grams' => (float) $food->gr ?: null,
            'kcal' => (float) $food->kcal,
            'protein' => (float) $food->protein,
            'fat' => (float) $food->lipid,
            'saturated_fat' => $food->saturated_fat === null ? null : (float) $food->saturated_fat,
            'cho' => (float) $food->cho,
            'glycemic_index' => $food->glycemic_index === null ? null : (int) $food->glycemic_index,
            'allergens' => array_values(array_filter(array_map('trim', explode(';', (string) $food->allergens)))),
            'price' => $food->price === null ? null : (float) $food->price,
        ];
    }

    /**
     * Nutrients of one exchange portion; glycemic load = glycemic index × carbohydrates / 100.
     */
    private function perPortion(Food $food): array
    {
        return [
            'energy' => (float) $food->kcal,
            'carbohydrates' => (float) $food->cho,
            'proteins' => (float) $food->protein,
            'fats' => (float) $food->lipid,
            'glycemic_load' => $food->glycemic_index === null ? 0.0 : $food->glycemic_index * (float) $food->cho / 100,
            'saturated_fat' => (float) $food->saturated_fat,
        ];
    }

    /**
     * MealItem of expert/app/responses.py.
     */
    private function item(Food $food, float $portions): array
    {
        return [
            'food_id' => $food->id,
            'name' => $food->name ?: $food->item,
            'group' => $food->item,
            'portions' => $portions,
            'grams' => (float) $food->gr ? (int) round($portions * (float) $food->gr) : null,
            ...array_map(fn ($value) => round($portions * $value, 1), $this->perPortion($food)),
        ];
    }

    private function sum(array $rows): array
    {
        return collect(self::REPORTED)
            ->mapWithKeys(fn ($key) => [$key => round(array_sum(array_column($rows, $key)), 1)])
            ->all();
    }
}
